import os

API_KEY = os.getenv("API_KEY", "2jkTcTMXlCHvV0uBtXeljMIOg")
API_SECRET = os.getenv("API_SECRET", "DcQwT8E8AWVibUMqGmJbfVtwdAhLoPUW1odTxFurClYl3gjZKy")
ACCESS_TOKEN = os.getenv("ACCESS_TOKEN", "1937648923667275776-FH63fObei7SioRmRLUy3WKs8IQi0RR")
ACCESS_TOKEN_SECRET = os.getenv("ACCESS_TOKEN_SECRET", "fN1i6hnsJkab3eTzxoA9CqE1JSMEs8zCaQumxzuy4VBVa")
BEARER_TOKEN = os.getenv("BEARER_TOKEN", "AAAAAAAAAAAAAAAAAAAAAN0y4AEAAAAABPDOTP%2BqaJV%2F6BaWvCyNMEqsITw%3DuTjvbybelmGAIjaHfSgfjcdSeOLFG3BlnevW3S2akq2pR7ghoQ")
