name: SpaceX Bot Automation

on:
  workflow_dispatch:  # Manual trigger
  push:
    branches:
      - main
  schedule:
    - cron: '*/20 * * * *'  # Every 20 minutes (0, 20, 40 past the hour)

jobs:
  run-bot:
    runs-on: ubuntu-latest
    timeout-minutes: 5  # Short timeout to prevent hangs
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run SpaceX Bot
        run: python spacex_bot.py
        env:
          API_KEY: ${{ secrets.API_KEY }}
          API_SECRET: ${{ secrets.API_SECRET }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
          BEARER_TOKEN: ${{ secrets.BEARER_TOKEN }}
